import 'package:freezed_annotation/freezed_annotation.dart';

enum Address {
  @JsonValue('北海道')
  hokkaido,
  @JsonValue('青森県')
  aomori,
  @JsonValue('岩手県')
  iwate,
  @JsonValue('宮城県')
  miyagi,
  @JsonValue('秋田県')
  akita,
  @JsonValue('山形県')
  yamagata,
  @JsonValue('福島県')
  fukushima,
  @JsonValue('茨城県')
  ibaraki,
  @JsonValue('栃木県')
  tochigi,
  @JsonValue('群馬県')
  gunma,
  @JsonValue('埼玉県')
  saitama,
  @JsonValue('千葉県')
  chiba,
  @JsonValue('東京都')
  tokyo,
  @JsonValue('神奈川県')
  kanagawa,
  @JsonValue('新潟県')
  niigata,
  @JsonValue('富山県')
  toyama,
  @JsonValue('石川県')
  ishikawa,
  @JsonValue('福井県')
  fukui,
  @JsonValue('山梨県')
  yamanashi,
  @JsonValue('長野県')
  nagano,
  @JsonValue('岐阜県')
  gifu,
  @JsonValue('静岡県')
  shizuoka,
  @JsonValue('愛知県')
  aichi,
  @JsonValue('三重県')
  mie,
  @JsonValue('滋賀県')
  shiga,
  @JsonValue('京都府')
  kyoto,
  @JsonValue('大阪府')
  osaka,
  @JsonValue('兵庫県')
  hyogo,
  @JsonValue('奈良県')
  nara,
  @JsonValue('和歌山県')
  wakayama,
  @JsonValue('鳥取県')
  tottori,
  @JsonValue('島根県')
  shimane,
  @JsonValue('岡山県')
  okayama,
  @JsonValue('広島県')
  hiroshima,
  @JsonValue('山口県')
  yamaguchi,
  @JsonValue('徳島県')
  tokushima,
  @JsonValue('香川県')
  kagawa,
  @JsonValue('愛媛県')
  ehime,
  @JsonValue('高知県')
  kochi,
  @JsonValue('福岡県')
  fukuoka,
  @JsonValue('佐賀県')
  saga,
  @JsonValue('長崎県')
  nagasaki,
  @JsonValue('熊本県')
  kumamoto,
  @JsonValue('大分県')
  oita,
  @JsonValue('宮崎県')
  miyazaki,
  @JsonValue('鹿児島県')
  kagoshima,
  @JsonValue('沖縄県')
  okinawa,
  @JsonValue('その他')
  others,
}
