// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnkGYOJGMaP5ikMDCbgldi-wvzzR4n04',
    appId: '1:590316043514:android:3f6ad4629a5bb3ec9e1d43',
    messagingSenderId: '590316043514',
    projectId: 'reimi-dev',
    storageBucket: 'reimi-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJx5tluHcvcwdPFKVuPTo7dm-e5CQhZ3I',
    appId: '1:590316043514:ios:2fc3f2b9214ce1f69e1d43',
    messagingSenderId: '590316043514',
    projectId: 'reimi-dev',
    storageBucket: 'reimi-dev.firebasestorage.app',
    androidClientId: '590316043514-73drhdgkebj8b5iup1ngas8sqcjlfvha.apps.googleusercontent.com',
    iosClientId: '590316043514-k2v56l7ku97bksiogihp3cfmds7iemej.apps.googleusercontent.com',
    iosBundleId: 'com.example.reimiApp.dev',
  );
}
