import 'package:freezed_annotation/freezed_annotation.dart';

enum Address {
  @JsonValue('HOKKAIDO')
  hokkaido,
  @JsonValue('AOMORI')
  aomori,
  @JsonValue('IWATE')
  iwate,
  @JsonValue('MIYAGI')
  miyagi,
  @JsonValue('AKITA')
  akita,
  @JsonValue('YAMAGATA')
  yamagata,
  @JsonValue('FUKUSHIMA')
  fukushima,
  @JsonValue('IBARAKI')
  ibaraki,
  @JsonValue('TOCHIGI')
  tochigi,
  @JsonValue('GUNMA')
  gunma,
  @JsonValue('SAITAMA')
  saitama,
  @JsonValue('CHIBA')
  chiba,
  @JsonValue('TOKYO')
  tokyo,
  @JsonValue('KANAGAWA')
  kanagawa,
  @JsonValue('NIIGATA')
  niigata,
  @JsonValue('TOYAMA')
  toyama,
  @JsonValue('ISHIKAWA')
  ishikawa,
  @JsonValue('FUKUI')
  fukui,
  @JsonValue('YAMANASHI')
  yamanashi,
  @JsonValue('NAGANO')
  nagano,
  @JsonValue('GIFU')
  gifu,
  @JsonValue('SHIZUOKA')
  shizuoka,
  @JsonValue('AICHI')
  aichi,
  @JsonValue('MIE')
  mie,
  @JsonValue('SHIGA')
  shiga,
  @JsonValue('KYOTO')
  kyoto,
  @JsonValue('OSAKA')
  osaka,
  @JsonValue('HYOGO')
  hyogo,
  @JsonValue('NARA')
  nara,
  @JsonValue('WAKAYAMA')
  wakayama,
  @JsonValue('TOTTORI')
  tottori,
  @JsonValue('SHIMANE')
  shimane,
  @JsonValue('OKAYAMA')
  okayama,
  @JsonValue('HIROSHIMA')
  hiroshima,
  @JsonValue('YAMAGUCHI')
  yamaguchi,
  @JsonValue('TOKUSHIMA')
  tokushima,
  @JsonValue('KAGAWA')
  kagawa,
  @JsonValue('EHIME')
  ehime,
  @JsonValue('KOCHI')
  kochi,
  @JsonValue('FUKUOKA')
  fukuoka,
  @JsonValue('SAGA')
  saga,
  @JsonValue('NAGASAKI')
  nagasaki,
  @JsonValue('KUMAMOTO')
  kumamoto,
  @JsonValue('OITA')
  oita,
  @JsonValue('MIYAZAKI')
  miyazaki,
  @JsonValue('KAGOSHIMA')
  kagoshima,
  @JsonValue('OKINAWA')
  okinawa,
  @JsonValue('OTHER')
  other,
}
