import 'package:flutter/material.dart';
import 'package:reimi_app/domain/value_objects/height.dart';
import 'package:reimi_app/core/i18n/strings.g.dart';

extension HeightExtension on Height {
  String displayName(BuildContext context) {
    final t = Translations.of(context).kEnum.height;
    switch (this) {
      case Height.under130cm:
        return t.under130cm;
      case Height.just131cm:
        return t.just131cm;
      case Height.just132cm:
        return t.just132cm;
      case Height.just133cm:
        return t.just133cm;
      case Height.just134cm:
        return t.just134cm;
      case Height.just135cm:
        return t.just135cm;
      case Height.just136cm:
        return t.just136cm;
      case Height.just137cm:
        return t.just137cm;
      case Height.just138cm:
        return t.just138cm;
      case Height.just139cm:
        return t.just139cm;
      case Height.just140cm:
        return t.just140cm;
      case Height.just141cm:
        return t.just141cm;
      case Height.just142cm:
        return t.just142cm;
      case Height.just143cm:
        return t.just143cm;
      case Height.just144cm:
        return t.just144cm;
      case Height.just145cm:
        return t.just145cm;
      case Height.just146cm:
        return t.just146cm;
      case Height.just147cm:
        return t.just147cm;
      case Height.just148cm:
        return t.just148cm;
      case Height.just149cm:
        return t.just149cm;
      case Height.just150cm:
        return t.just150cm;
      case Height.just151cm:
        return t.just151cm;
      case Height.just152cm:
        return t.just152cm;
      case Height.just153cm:
        return t.just153cm;
      case Height.just154cm:
        return t.just154cm;
      case Height.just155cm:
        return t.just155cm;
      case Height.just156cm:
        return t.just156cm;
      case Height.just157cm:
        return t.just157cm;
      case Height.just158cm:
        return t.just158cm;
      case Height.just159cm:
        return t.just159cm;
      case Height.just160cm:
        return t.just160cm;
      case Height.just161cm:
        return t.just161cm;
      case Height.just162cm:
        return t.just162cm;
      case Height.just163cm:
        return t.just163cm;
      case Height.just164cm:
        return t.just164cm;
      case Height.just165cm:
        return t.just165cm;
      case Height.just166cm:
        return t.just166cm;
      case Height.just167cm:
        return t.just167cm;
      case Height.just168cm:
        return t.just168cm;
      case Height.just169cm:
        return t.just169cm;
      case Height.just170cm:
        return t.just170cm;
      case Height.just171cm:
        return t.just171cm;
      case Height.just172cm:
        return t.just172cm;
      case Height.just173cm:
        return t.just173cm;
      case Height.just174cm:
        return t.just174cm;
      case Height.just175cm:
        return t.just175cm;
      case Height.just176cm:
        return t.just176cm;
      case Height.just177cm:
        return t.just177cm;
      case Height.just178cm:
        return t.just178cm;
      case Height.just179cm:
        return t.just179cm;
      case Height.just180cm:
        return t.just180cm;
      case Height.just181cm:
        return t.just181cm;
      case Height.just182cm:
        return t.just182cm;
      case Height.just183cm:
        return t.just183cm;
      case Height.just184cm:
        return t.just184cm;
      case Height.just185cm:
        return t.just185cm;
      case Height.just186cm:
        return t.just186cm;
      case Height.just187cm:
        return t.just187cm;
      case Height.just188cm:
        return t.just188cm;
      case Height.just189cm:
        return t.just189cm;
      case Height.just190cm:
        return t.just190cm;
      case Height.just191cm:
        return t.just191cm;
      case Height.just192cm:
        return t.just192cm;
      case Height.just193cm:
        return t.just193cm;
      case Height.just194cm:
        return t.just194cm;
      case Height.just195cm:
        return t.just195cm;
      case Height.just196cm:
        return t.just196cm;
      case Height.just197cm:
        return t.just197cm;
      case Height.just198cm:
        return t.just198cm;
      case Height.just199cm:
        return t.just199cm;
      case Height.over200cm:
        return t.over200cm;
    }
  }
}
